# Generated by Django 4.1.4 on 2022-12-10 11:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=750, null=True, populate_from='question', unique=True),
        ),
    ]
